'''
File: keplerConfig.py
Purpose: Hold function to create kepler.gl config information
Created by: Alton Hipps
Last edited: 07/30/25
'''
from datetime import datetime

def createDateRange(inDf):
    maxDate=inDf['TimeStamp'].max()
    maxDateObj=maxDate#datetime(year=int(str(maxDate)[0:4]),month=int(str(maxDate)[5:7]),day=int(str(maxDate)[8:10]))
    unixMax = int(str(maxDateObj.timestamp())[:-2]+'00')

    minDate=inDf['TimeStamp'].min()
    minDateObj=minDate#datetime(year=int(str(minDate[0:4])),month=int(minDate[5:7]),day=int(minDate[8:10]))
    unixMin = int(str(minDateObj.timestamp())[:-2]+'00')
    return (unixMin,unixMax)

def createConfig(rtDes,dateRange):
    outConfig={
        'version': 'v1',
        "config":{
            "visState":{
                "filters":[{
                    "dataId":[f"Rt{rtDes}"],
                    "id":f"Rt{rtDes}_timestamp",
                    "name":["TimeStamp"],
                    "type":"timeRange", 
                    "value":[dateRange[0],dateRange[1]],
                    "plotType":{
                        "interval":"6-hour",
                        "defaultTimeFormat":"L  H A",
                        "type":"histogram",
                        "aggregation":"sum"
                        },
                    "animationWindow":"free",
                    "yAxis":'null',
                    "view":"enlarged",
                    "speed":0.05,
                    "enabled":'true'
                    }
                ],
                "layers":[{
                    "id":f"-Rt{rtDes}_id",
                    "type":"geojson",
                    "config":{
                        "dataId":f"Rt{rtDes}",
                        "columnMode":"geojson",
                        "label":f"Bus Fullness - Route {rtDes}",
                        "color":[34,63,154],
                        "highlightColor":[252,242,26,255],
                        "columns":{"geojson":"geometry"},
                        "isVisible":'true',
                        "visConfig":{
                            "opacity":0.8,
                            "strokeOpacity":0.8,
                            "thickness":0.5,
                            "strokeColor":'null',
                            "colorRange":{
                                "colors":["#FAE300","#CF1750","#223F9A"],
                                "name":"UberPool",
                                "type":"diverging",
                                "category":"Uber",
                                "reversed":True,
                                "colorMap":[["EMPTY","#FAE300"],["FULL","#CF1750"],["HALF_EMPTY","#223F9A"]]
                                },
                            "strokeColorRange":{
                                "name":"Global Warming",
                                "type":"sequential",
                                "category":"Uber",
                                "colors":[
                                    "#4C0035",
                                    "#880030",
                                    "#B72F15",
                                    "#D6610A",
                                    "#EF9100",
                                    "#FFC300"
                                    ]
                                },
                            "radius":10,
                            "sizeRange":[0,10],
                            "radiusRange":[0,50],
                            "heightRange":[0,500],
                            "elevationScale":5,
                            "stroked":False,
                            "filled":True,
                            "enable3d":False,
                            "wireframe":False,
                            "fixedHeight":False
                            },
                        "hidden":False,
                        "textLabel":[{
                            "field":'Fullness',
                            "color":[255,255,255],
                            "size":18,
                            "offset":[0,0],
                            "anchor":"start",
                            "alignment":"center",
                            "outlineWidth":0,
                            "outlineColor":[255,0,0,255],
                            "background":'false',
                            "backgroundColor":[0,0,200,255]
                            }]
                    },
                    "visualChannels":{
                        "colorField":{
                            "name":"Fullness","type":"string"
                        },
                        "colorScale":"customOrdinal",
                        "strokeColorField":'null',
                        "strokeColorScale":"quantile",
                        "sizeField":'null',
                        "sizeScale":"linear",
                        "heightField":'null',
                        "heightScale":"linear",
                        "radiusField":'null',
                        "radiusScale":"linear"
                        }
                }],
                "effects":[],
                "interactionConfig":{
                    "tooltip":{
                        "fieldsToShow":{
                            "-RtA_id":[{
                                    "name":"DelayStatus",
                                    "format":'null'
                                },{
                                    "name":"Destination",
                                    "format":'null'
                                },{
                                    "name":"Fullness",
                                    "format":'null'
                                },{
                                    "name":"Speed",
                                    "format":'null'
                                }]
                        },
                        "compareMode":False,
                        "compareType":"absolute",
                        "enabled":True
                    },
                    "brush":{
                        "size":0.5,
                        "enabled":False
                    },
                    "geocoder":{
                        "enabled":False
                    },
                    "coordinate":{
                        "enabled":False
                    }
                },
                "layerBlending":"additive",
                "overlayBlending":"screen",
                "splitMaps":[],
                "animationConfig":{
                    "currentTime":'null',
                    "speed":1
                },
                "editor":{
                    "features":[],
                    "visible":False
                }
            },
            "mapState":{
                "bearing":0,
                "dragRotate":False,
                "latitude":43.07794042346403,
                "longitude":-89.37636850809596,
                "pitch":20,
                "zoom":11,
                "isSplit":False,
                "isViewportSynced":True,
                "isZoomLocked":False,
                "splitMapViewports":[]
            },'''
            "mapStyle":{
                "styleType":"dark-matter",
                "topLayerGroups":{},
                "visibleLayerGroups":{
                    "label":True,
                    "road":True,
                    "border":False,
                    "building":True,
                    "water":True,
                    "land":True,
                    "3d building":False
                },
                "threeDBuildingColor":[15.035172933000911,15.035172933000911,15.035172933000911],
                "backgroundColor":[0,0,0],
                "mapStyles":{}
            },'''
            "uiState":{
                "mapControls":{
                    "mapLegend":{
                        "active":True
                    }
                }
            }
        }
    }
    return outConfig